# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 339d728ce1cbd8e7fd9918103ba6278b0c55cffc6fc9417b729aab5b972f88da9093c2513662bb0cfadc41e2cb9804dbf94a92026d3c51a77d1eb560b48de8fd

test:
  secret_key_base: e2c5bf1c003b5949a3812f4fabf7fc14580c16bd691b2f4f5c228db25cd5b142ab36f78d7888f84d37e2fa9933eac9a246f026c99b40e0a333aa5d8737055ab4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
